EMERGE_DEFAULT_OPTS="--buildpkg --usepkg --with-bdeps=y"

BINPKG_GPG_SIGNING_KEY="AFF6DFAE8CEC37E607696622B4C778986842630B"
BINPKG_COMPRESS="zstd"
BINPKG_COMPRESS_FLAGS="-19 -T4 --long"
FEATURES="binpkg-signing gpg-keepalive"
BINPKG_GPG_SIGNING_GPG_HOME="/var/lib/portage/gnupg-sign"
INSTALL_MASK="/boot"

# Temp just for remembering
SECUREBOOT_SIGN_KEY="/root/secureboot/db.key"
SECUREBOOT_SIGN_CERT="/root/secureboot/db.pem"
MODULES_SIGN_KEY="/root/secureboot/db.key"
MODULES_SIGN_CERT="/root/secureboot/db.pem"
